my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: razor-project-339321
      dataset: trips_data_all
      threads: 2
      keyfile: /home/cristiandugacicu/projects/personal/de-zoomcamp/secrets/razor-project-339321-3a382dd6a910.json

